
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 27 20:48:36 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 21;
  public static final int ELSE = 4;
  public static final int DECIMAL = 27;
  public static final int GREATER_THAN = 17;
  public static final int WHILE = 5;
  public static final int DIVISION = 10;
  public static final int OPENING_BRACE = 13;
  public static final int OPENING_PARENTHESIS = 11;
  public static final int CLOSING_BRACKET = 16;
  public static final int RETURN = 29;
  public static final int IDENTIFIER = 25;
  public static final int ERROR = 30;
  public static final int STRING_DATATYPE = 24;
  public static final int DECIMAL_DATATYPE = 23;
  public static final int CLOSING_PARENTHESIS = 12;
  public static final int IF = 2;
  public static final int INTEGER_DATATYPE = 22;
  public static final int STRING = 28;
  public static final int EQUALS = 6;
  public static final int EOF = 0;
  public static final int SUBTRACTION = 8;
  public static final int MAIN = 19;
  public static final int MULTIPLICATION = 9;
  public static final int LESS_THAN = 18;
  public static final int PRINT = 20;
  public static final int error = 1;
  public static final int CLOSING_BRACE = 14;
  public static final int INTEGER = 26;
  public static final int OPENING_BRACKET = 15;
  public static final int FOR = 3;
  public static final int ADDITION = 7;
}

